CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers (
id INT(100) AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(100) NULL,
devoured BOOLEAN,
date TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)

SELECT * FROM burgers;
